# Generated by Django 5.1.2 on 2024-10-19 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="preregister_candidates",
            field=models.BooleanField(
                default=True, verbose_name="preregister candidates"
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="candidates",
            field=models.ManyToManyField(
                blank=True, to="quiz.candidate", verbose_name="candidates"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="name",
            field=models.CharField(max_length=16, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="name",
            field=models.CharField(max_length=64, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="season",
            name="active_quiz",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="quiz.quiz",
                verbose_name="active quiz",
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="name",
            field=models.CharField(max_length=64, verbose_name="name"),
        ),
    ]
