# Generated by Django 5.1.3 on 2024-11-30 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="owner",
            field=models.ManyToManyField(
                related_name="seasons",
                to=settings.AUTH_USER_MODEL,
                verbose_name="owners",
            ),
        ),
    ]
