# Generated by Django 5.1.2 on 2024-11-03 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_season_preregister_candidates_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="givenanswer",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="givenanswer",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="given_answers",
                to="quiz.question",
                verbose_name="question",
            ),
        ),
    ]
