# Generated by Django 5.1.3 on 2024-12-01 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_season_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="correction",
            name="amount",
            field=models.FloatField(default=1, verbose_name="amount"),
        ),
        migrations.AlterField(
            model_name="correction",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="corrections",
                to="quiz.candidate",
                verbose_name="candidate",
            ),
        ),
        migrations.AlterField(
            model_name="correction",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="corrections",
                to="quiz.quiz",
                verbose_name="quiz",
            ),
        ),
    ]
