# Generated by Django 5.1.3 on 2024-12-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_correction_amount_alter_correction_candidate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="dropouts",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="dropouts"),
        ),
    ]
