# Generated by Django 5.1.3 on 2024-11-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_givenanswer_created_alter_givenanswer_question"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="question",
            unique_together=set(),
        ),
        migrations.AlterOrderWithRespectTo(
            name="question",
            order_with_respect_to="quiz",
        ),
        migrations.AlterOrderWithRespectTo(
            name="answer",
            order_with_respect_to="question",
        ),
        migrations.RemoveField(
            model_name="question",
            name="number",
        ),
    ]
